name: Two-Factor Authentication 2FA Chainlink External Adapter
description: This adapter is an extra layer of security where in addition to a password the user must confirm a code from/click a button on a trusted device only they have access to.
node_identifier: 2fa-cl-ea
platforms:
  - Docker
  - Lambda
  - GCP Functions
parameters:
  - customerid
  - hashedpin
