name: 2FA Chainlink EA
description: This adapter is an extra layer of security where in addition to a password the user must confirm a code from/click a button on a trusted device only they have access to.
node_identifier: 2fa-cl-ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
parameters:
  - customerid
  - hashedpin
